manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kbrd-space
      url-base: https://github.com/kbrd-space
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-anti-idle
      remote: zmkfirmware
      revision: main                # or the latest release tag
      import: app/modules/anti-idle # imports into zmk/app/module/anti-idle
  self:
    path: config
